schema_version: 1

context:
  name: neuron
  version: 8.2.4
  build: 1

package:
  name: ${{ name | lower }}
  version: ${{ version }}

source:
  - url: https://github.com/neuronsimulator/nrn/releases/download/${{ version }}/nrn-full-src-package-${{ version }}.tar.gz
    sha256: 35654c1af7e198b53b34c923be5913d5c98fbc0e2d15515ef9157ef2fdff1e52

build:
  number: ${{ build }}
  string: mpi_mpich_h${{ hash }}_${{ build }}

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - make
    - cmake <4
    - bison
    - flex
    - pkg-config
    - libtool
  host:
    - python 3.12.*
    - cython <3.0
    - setuptools
    - setuptools_scm
    - wheel
    - numpy
    - readline
    - ncurses
    - xorg-libx11
    - xorg-libxcomposite
    - xorg-libxext
    - xorg-xorgproto
    - mpich
  run:
    - python 3.12.*
    - numpy
    - packaging
    - readline
    - ncurses
    - setuptools
    - ${{ pin_compatible('xorg-libx11') }}
    - ${{ pin_compatible('xorg-libxcomposite') }}
    - ${{ pin_compatible('xorg-libxext') }}
    - mpich
  run_exports:
    - ${{ pin_subpackage(name, exact=True) }}

tests:
  - python:
      imports:
        - neuron
        - neuron.rxd
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
      run:
        - make
        - scipy
    files:
      source:
        - pump.mod
        - test_mpi.py
about:
  homepage: https://neuron.yale.edu
  license: BSD-3-Clause
  license_file: Copyright
  summary: NEURON is a simulator for models of neurons and networks of neuron.

extra:
  recipe-maintainers:
    - minrk